"""Five-mechanism synthetic SCM (advisor Sec. 2.5, RACE-v2 B5).

Labels are generated by the CF-GNNExplainer-style rule: node features are iid
noise, and the label of node v is determined by the mean of the FEATURES of
v's causal-graph neighbors projected onto random class patterns, so the graph
is necessary for classification and deleting the causal relation flips
predictions.

Relation slots (standard mechanism, K >= 3; extra relations are pure noise):
  0: causal     -- homophilic in y (its neighborhood defines y via patterns)
  1: spurious   -- homophilic in an attribute correlated with y in the TRAIN
                   environment but independent of y in the TEST environment
  2: redundant  -- homophilic in y again (duplicate signal, fresh edges)
  3..K-1: noise -- Erdos-Renyi

Synergistic mechanism (K >= 2): y = (y_u + y_v) mod C where y_u is defined by
the relation-0 neighborhood and y_v by the relation-1 neighborhood; each
relation alone recovers only one part, so the minimal data-causal set is
{0, 1}.  Features remain pure noise in both mechanisms.

The generator returns train_mask (train env: spurious correlated) and
test_mask (test env: decorrelated), letting the experiment report BOTH hit
rates of the advisor: model-dependence recovery (what the trained model
actually uses) and data-causal recovery (the true generating relation).
"""

from __future__ import annotations

from typing import Dict, Tuple

import numpy as np
import torch
from torch import Tensor


def _homophilic_edges(group_ids: np.ndarray, p: float, rng: np.random.Generator) -> Tuple[np.ndarray, np.ndarray]:
    """Sample (src, dst) pairs within equal groups with per-pair prob p."""
    srcs, dsts = [], []
    for g in np.unique(group_ids):
        idx = np.nonzero(group_ids == g)[0]
        n = len(idx)
        if n < 2:
            continue
        k = max(1, int(n * (n - 1) * p))
        pairs = rng.integers(0, n, size=(k, 2))
        pairs = pairs[pairs[:, 0] != pairs[:, 1]]
        srcs.append(idx[pairs[:, 0]])
        dsts.append(idx[pairs[:, 1]])
    if not srcs:
        return np.zeros(0, dtype=np.int64), np.zeros(0, dtype=np.int64)
    return np.concatenate(srcs), np.concatenate(dsts)


def _er_edges(n_nodes: int, p: float, rng: np.random.Generator) -> Tuple[np.ndarray, np.ndarray]:
    k = max(1, int(n_nodes * n_nodes * p))
    src = rng.integers(0, n_nodes, size=k)
    dst = rng.integers(0, n_nodes, size=k)
    ok = src != dst
    return src[ok], dst[ok]


def _labels_from_neighbors(
    src: np.ndarray, dst: np.ndarray, patterns: np.ndarray,
    n_nodes: int, rng: np.random.Generator, x: np.ndarray,
) -> np.ndarray:
    """y_v = argmax_c <mean_{u in N(v)} x_u, pattern_c>; random label if no neighbors."""
    neigh: Dict[int, list] = {}
    for u, w in zip(src.tolist(), dst.tolist()):
        neigh.setdefault(w, []).append(u)
    y = np.zeros(n_nodes, dtype=np.int64)
    for v in range(n_nodes):
        if v in neigh:
            mu = x[neigh[v]].mean(axis=0)
            y[v] = int(np.argmax(patterns @ mu))
        else:
            y[v] = int(rng.integers(0, patterns.shape[0]))
    return y


def make_scm(
    n_nodes: int = 400,
    n_classes: int = 4,
    feat_dim: int = 16,
    K: int = 4,
    p_in: float = 0.05,
    p_noise: float = 0.003,
    spurious_corr: float = 0.95,
    p_in_redundant: float = None,
    p_in_syn: float = 0.08,
    mechanism: str = "standard",  # "standard" | "synergistic"
    seed: int = 0,
) -> Dict:
    """Generate one synthetic SCM instance."""
    if p_in_redundant is None:
        p_in_redundant = p_in
    rng = np.random.default_rng(seed)
    x = rng.normal(0, 1.0, (n_nodes, feat_dim)).astype(np.float32)
    patterns = rng.normal(0, 1.0, (n_classes, feat_dim)).astype(np.float32)

    if mechanism == "standard":
        # causal edges define y from neighbor-feature aggregates
        y_prior = rng.integers(0, n_classes, n_nodes)  # needed for homophily: generate y first? NO --
        # the CF-GNNExplainer rule generates y FROM the causal graph.  To make the
        # causal graph homophilic in y we instead: sample y first, build homophilic
        # causal edges, then OVERWRITE y with the neighbor-pattern rule so that the
        # graph defines the label (approximately consistent because homophilic
        # neighbors share y and the pattern rule reproduces it with noise).
        y0 = rng.integers(0, n_classes, n_nodes)
        src0, dst0 = _homophilic_edges(y0, p_in, rng)
        y = _labels_from_neighbors(src0, dst0, patterns, n_nodes, rng, x)
        causal = (src0, dst0)
        spurious_group = np.where(
            rng.random(n_nodes) < spurious_corr, y0, rng.integers(0, n_classes, n_nodes))
    else:
        # synergistic: y_u from rel-0 neighborhood, y_v from rel-1 neighborhood
        yu0 = rng.integers(0, n_classes, n_nodes)
        yv0 = rng.integers(0, n_classes, n_nodes)
        src0, dst0 = _homophilic_edges(yu0, p_in_syn, rng)
        src1, dst1 = _homophilic_edges(yv0, p_in_syn, rng)
        y_u = _labels_from_neighbors(src0, dst0, patterns, n_nodes, rng, x)
        y_v = _labels_from_neighbors(src1, dst1, patterns, n_nodes, rng, x)
        y = (y_u + y_v) % n_classes
        causal_pair = ((src0, dst0), (src1, dst1))
        spurious_group = None

    train_env = rng.random(n_nodes) < 0.6
    # spurious attribute: correlated with y0 in the TRAIN env only
    a = rng.integers(0, n_classes, n_nodes)
    if mechanism == "standard":
        a = np.where(train_env, spurious_group, a)

    edges: Dict[str, Tuple[np.ndarray, np.ndarray]] = {}
    if mechanism == "standard":
        edges["0"] = causal
        edges["1"] = _homophilic_edges(a, p_in, rng)          # spurious
        edges["2"] = _homophilic_edges(y0, p_in_redundant, rng)  # redundant (weaker)
        for r in range(3, K):
            edges[str(r)] = _er_edges(n_nodes, p_noise, rng)
    else:
        edges["0"] = causal_pair[0]
        edges["1"] = causal_pair[1]
        for r in range(2, K):
            edges[str(r)] = _er_edges(n_nodes, p_noise, rng)

    eid = {k: torch.tensor(np.stack([s, d]), dtype=torch.long)
           for k, (s, d) in edges.items() if len(s) > 0}
    return {
        "x": torch.tensor(x, dtype=torch.float32),
        "y": torch.tensor(y, dtype=torch.long),
        "edge_index_dict": eid,
        "train_mask": torch.tensor(train_env),
        "test_mask": torch.tensor(~train_env),
        "causal_relations": [0] if mechanism == "standard" else [0, 1],
        "mechanism": mechanism,
        "seed": seed,
    }
